version: "3.9"

services:
  cerebro:
    depends_on:
      - elasticsearch
    image: lmenezes/cerebro:${CEREBRO_VERSION}
    container_name: cerebro
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
    ports:
      - "9000:9000"
    networks: 
      - elk

  logstash:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    container_name: logstash
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
    ports:
      - "9600:9600"
    networks:
      - elk

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    volumes:
      - kibanaData:/usr/share/kibana
    ports:
      - "5601:5601"
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: es01
    restart: unless-stopped
    environment:
      - node.name=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=${CLUSTER_NAME}
      - network.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300" 
    networks: 
      - elk

networks:
  elk:
    driver: bridge

volumes:
  esdata01:
    driver: local
  kibanaData:
    driver: local