FROM alpine:latest

WORKDIR /opt

RUN set -x \
    && wget -t1 -T2 https://gist.githubusercontent.com/UNICKCHENG/c42a9fbc58cdb883f1b154a6048e4980/raw/9e7b0cf0163db336119849db5fab0743167c62c6/info_os_and_cpu.sh \
    && info=`sh info_os_and_cpu.sh "AdguardTeam/AdGuardHome" | grep AdGuardHome | awk -F ":" '{print $2}'` && rm -f info_os_and_cpu.sh \
    && wget -O AdGuardHome.tar.gz -t1 -T2 https://github.com/AdguardTeam/AdGuardHome/releases/download/$(echo $info | awk -F "-" '{print $3}')/AdGuardHome_$(echo $info | awk -F "-" '{print $1 "_" $2}').tar.gz \
    && tar zxvf AdGuardHome.tar.gz && rm -f AdGuardHome.tar.gz 

CMD ["--no-check-update","-c","/opt/AdGuardHome/conf/AdGuardHome.yaml",\
        "-h","0.0.0.0","-w","/opt/AdGuardHome/work"]
ENTRYPOINT ["/opt/AdGuardHome/AdGuardHome"]