FROM alpine:latest

WORKDIR /opt

RUN set -x \
    && wget -t1 -T2 https://raw.githubusercontent.com/UNICKCHENG/Tools-Deployment/main/Scripts/info_os_and_cpu.sh \
    && info=`sh info_os_and_cpu.sh "AdguardTeam/AdGuardHome" | grep AdGuardHome | awk -F ":" '{print $2}'` && rm -f info_os_and_cpu.sh \
    && wget -O AdGuardHome.tar.gz -t1 -T2 https://github.com/AdguardTeam/AdGuardHome/releases/download/$(echo $info | awk -F "-" '{print $3}')/AdGuardHome_$(echo $info | awk -F "-" '{print $1 "_" $2}').tar.gz \
    && tar zxvf AdGuardHome.tar.gz && rm -f AdGuardHome.tar.gz 

CMD ["--no-check-update","-c","/opt/AdGuardHome/conf/AdGuardHome.yaml",\
        "-h","0.0.0.0","-w","/opt/AdGuardHome/work"]
ENTRYPOINT ["/opt/AdGuardHome/AdGuardHome"]